language: python
python:
  - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements.txt
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database test_learning_journal;' -U postgres
# command to run tests, e.g. python setup.py test
script: py.test
